#ifndef ORG_PP_QQ_COMMON_PREPROCESS_PREPROCESS_H
#define ORG_PP_QQ_COMMON_PREPROCESS_PREPROCESS_H


#define PP_QQ_CONCAT_DIRECT(x,y) x ## y
#define PP_QQ_CONCAT_WITH_EXPAND(x,y) PP_QQ_CONCAT_DIRECT(x,y)


#define PP_QQ_ANONYMOUS_NAME(var) PP_QQ_CONCAT_WITH_EXPAND(var,__LINE__)


#endif // ORG_PP_QQ_COMMON_PREPROCESS_PREPROCESS_H
